### ISSUE TITLE
[Feature Request] - Documentation Improvement on Custom Rules

### ISSUE THREAD

**Issue by marcopinder** [forcedotcom/sfdx-scanner#1214]
**Is your feature request related to a problem? Please describe.**
I feel it isn't clear in the SFCA site documentation on how to use custom rules as either a replacement for existing rules, or alongside the built-in rules - especially in the context of the pmd engine.

**Describe the solution you'd like**
Explain the differences between the `scanner:rule:add` and `--pmdconfig` exactly as @jfeingold35 did in point 1 in [this comment](https://github.com/forcedotcom/sfdx-scanner/issues/1104#issuecomment-1622683781).

**Describe alternatives you've considered**
No alternative considered.

**Additional context**
N/A

"Workaround": N/A

"Urgency": How badly do you need this feature? "Nice to have" vs "Highly beneficial" vs "Can't live without it". Highly beneficial to have clear documentation.

**Comment by marcopinder** [comment]
@jfeingold35 I have poured over all these pages for hours. Perhaps it is my interpretation - it just doesn't come across as clear enough to me that there is a difference between running the default pmd rules in sfca, and entirely replacing them with my own version (with a subset commented out - which may or may not reference other xml files with custom rules). I'm doing some tests in a repo right now using @mitchspano 's GitHub Action as I am not getting the same result as when using the same commands locally on my machine. Hopefully @rsoesemann doesn't mind me mentioning his comment [here](https://github.com/forcedotcom/sfdx-scanner/issues/1104#issuecomment-1749135808) as there is still confusion about adding rules beforehand, versus specifying the `--pmdconfig` and what outcome is achieved either way.

**Comment by rsoesemann** [comment]
Indeed @marcopinder I am also still confused but it looks to me that the sfca has its own internal ruleset to make sure it checks the things Salesforce is interested in. When you like I want to use the sfca as a runner for PMD and other tools just feed it your own ruleset and it will ignore the internal stuff.

The add command is needed when you want both. E.g. run Salesforce own Security (Review) rules and still have your stuff on top.

And I totally agree. For such a lightweight tool the Github pages is bloated and confusing.

**Comment by stephen-carter-at-sf** [comment]
With Code Analyzer v5, you'll be able to easily run the bundled pmd rules alongside your own custom pmd rules. You'll see that you can create a code-analyzer.yml file and include your custom rulesets and jar files with:
```
engines:
  pmd:
    # List of jar files and/or folders to add the Java classpath when running PMD.
    # Each entry may be given as an absolute path or a relative path to 'config_root'.
    # This field is primarily used to supply custom Java based rule definitions to PMD.
    # See https://pmd.github.io/pmd/pmd_userdocs_extending_writing_java_rules.html
    java_classpath_entries: []

    # List of xml ruleset files containing custom PMD rules to be made available for rule selection.
    # Each ruleset must be an xml file that is either:
    #   - on disk (provided as an absolute path or a relative path to 'config_root')
    #   - or a relative resource found on the Java classpath.
    # Not all custom rules can be fully defined within an xml ruleset file. For example, Java based rules may be defined in jar files.
    # In these cases, you will need to also add your additional files to the Java classpath using the 'java_classpath_entries' field.
    # See https://pmd.github.io/pmd/pmd_userdocs_making_rulesets.html to learn more about PMD rulesets.
    custom_rulesets: []
```
Then you'll be able to do:
```
sf code-analyzer rules -r pmd:Recommended
```
to confirm your rules are listed
and then you can run with
```
sf code-analyzer run -r pmd:Recommended
```
Learn more over at: https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/code-analyzer.html
