### ISSUE TITLE
[BUG] Error installing SFDX Scanner on Github actions pipeline.

### ISSUE THREAD

**Issue by rosangelys-pfm** [forcedotcom/sfdx-scanner#1522]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

I have a CI/CD job running with github actions where it used to work fine but I am now getting the following error when trying to install the SFDX Scanner for code scanning:

Installing plugin @salesforce/sfdx-scanner... ⣻ [2/4] Fetching packages...
error @typescript-eslint/parser@7.14.1: The engine "node" is incompatible with this module. Expected version "^18.18.0 || >=20.0.0". Got "18.15.0"
error Found incompatible module.
Installing plugin @salesforce/sfdx-scanner... ⢿ info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Installing plugin @salesforce/sfdx-scanner... failed
    Error: yarn add @salesforce/sfdx-scanner@latest --non-interactive 
    --mutex=file:/home/runner/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/runner/.cache/sfdx/yarn --check-files 
    exited with code 1
Error: Process completed with exit code 1.

I installed the node version in my github pipeline as follows:
# Install nodejs in the VM, and specify version 
            - name: 'Install NodeJS'
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

This is the installing version: 18.20.3

### Output / Logs

Node version:
<img width="1105" alt="Node V" src="https://github.com/forcedotcom/sfdx-scanner/assets/167131175/95439ed5-e093-4b8e-91e7-0881cb295f76">

Error:
<img width="1119" alt="Error sfdx" src="https://github.com/forcedotcom/sfdx-scanner/assets/167131175/e925e280-4777-4d62-8dcf-66935c3fa5d2">

### Steps To Reproduce

Trigger Github workflow
Installation of node step is done
SFDX installation is made

### Expected Behavior

The installations are made successfully and code is scanned.

### Operating System

Github Workflow VM:  Ubuntu   22.04.4   LTS

### Salesforce CLI Version

sfdx-cli/7.209.6 linux-x64 node-v18.15.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner (latest)

### Urgency

High

**Comment by Bheru-gadri** [comment]
It's fixed and working fine for me. I just added a new step after the 'Install Node JS' step.
 
```
 - name: 'Ignore engines from yarn'
        run: |
            echo "Ignore engines"
            yarn config set ignore-engines true 
```

**Comment by Sachhiin** [comment]
Hi @Bheru-gadri,
I'm facing the same issue.
Can you provide the entire YML file for reference?

Thanks

**Comment by Sachhiin** [comment]
I'm using bitbucket pipeline for deployment and facing this issue

**Comment by lucas-tesan** [comment]
Thanks for reporting, we are facing the same issue

**Comment by rosangelys-pfm** [comment]
For me, the problem was the node version that the SFDX CLI installation was installing too as a bundle. Fixed it by doing the following:

- Updating node version being installed at the beginning of YML:
```
# Install nodejs in the VM, and specify version 20
            - name: 'Install NodeJS'
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
```

- Installing the latest version of SF CLI (Previously using installation with URL to tar.xz file) 
PREVIOUS:
```
# Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                  mkdir ~/sfdx
                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                  ~/sfdx/bin/sfdx version
```
CURRENT (fixed the problem for me):
```
# Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  npm install sfdx-cli --global
```

**Comment by stephen-carter-at-sf** [comment]
We just updated @salesforce/sfdx-scanner@latest to version 4.0 which contains updates to eslint which require your node version to either be 18.18.0+ or 20.0.0+. Additionally we now require the JAVA version to 11 or greater.

Note that if you have the latest version of the sf cli then you should have node version 20+ already available.

So you have a few options:
* Upgrade to the latest sf cli with: `npm install -g @salesforce/cli@latest`
* Upgrade your node environment to v20 with 
            - name: 'Install NodeJS'
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
* or forcefully downgrade the @salesforce/sfdx-scanner to v3.26.0 with: `sf plugins install @salesforce/sfdx-scanner@3.26.0`

May I also recommend that you use the [run code analyzer GitHub action](https://github.com/marketplace/actions/run-salesforce-code-analyzer) that we offer.

**Comment by sandeepkumargetweave** [comment]
@rosangelys-pfm it has fixed the issue on our side as well. Thanks!

**Comment by johnbelosf** [comment]
Please see @stephen-carter-at-sf 's comment above to resolve this issue. Closing for now.

**Comment by johnbelosf** [comment]
Reopening for wider awareness for the time being

**Comment by Sachhiin** [comment]
Hi @stephen-carter-at-sf I'm still facing issue/error for bitbucket pipeline.
I have tried with node - 20 bullseye, 22-bullseye, 22.3.0

Can you suggest any workaround?

**Comment by stephen-carter-at-sf** [comment]
@Sachhiin what do you get for  `sf --version`?
And what exactly is the error that you are seeing?

**Comment by sandeepkumargetweave** [comment]
@stephen-carter-at-sf we tried using Salesforce Code Analyser but seeing the below error while executing the workflow, looks like we are missing some configuration to store the output file.

![image](https://github.com/forcedotcom/sfdx-scanner/assets/89843810/251bb1df-1b69-4ad6-9be4-c17debaeb41b)

**Comment by sandeepkumargetweave** [comment]
[rosangelys-pfm](https://github.com/rosangelys-pfm) The issue is not completely resolved for us. It worked intermittently but now it is not working at all. Could you share your complete YAML file w.r.t SFDC Scanner ?

**Comment by stephen-carter-at-sf** [comment]
[sandeepkumargetweave](https://github.com/sandeepkumargetweave) Can you share your github workflow file and the entire log output of your github workflow job?

**Comment by rosangelys-pfm** [comment]
> [rosangelys-pfm](https://github.com/rosangelys-pfm) The issue is not completely resolved for us. It worked intermittently but now it is not working at all. Could you share your complete YAML file w.r.t SFDC Scanner ?

This runs when our GitHub Pull Requests are opened

```
# Jobs to be executed when the above conditions are met
jobs:
    validate-deployment-on-UAT-org:
        env:
            SF_SCANNER_OUTFILE: 'scanner-output/scannerResult.xml'
            SF_SCANNER_FORMAT: 'csv'
            SF_SCANNER_SEVERITY: 3
            STG_ORG_ALIAS: UAT-STAGING
            AB_ORG_ALIAS: AB-SDBX-STAGING
            SFDX_HIDE_RELEASE_NOTES_FOOTER: true
            SFDX_HIDE_RELEASE_NOTES: true
        runs-on: ubuntu-latest
        steps:
            # Install nodejs in the VM, and specify version 20
            - name: 'Install NodeJS'
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            # Checkout the source code
            # The fetch-depth:0  allows us to access previous commits that have been pushed to the repository.

            # We'll need this later when we try to figure out which metadata has
            # changed between commits, so that we can only deploy that metadata
            # to the destination org
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  npm install sfdx-cli --global

            # Install the SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
            # This plugin allows us to extract a package.xml with the metadata that has changed between commits.
            - name: 'Installing sfdx git delta'
              run: |
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins

            # Install java as it is required for the next step
            - name: 'Installing java'
              run: |
                  sudo apt-get update
                  sudo apt install default-jdk

            # Install SFDX scanner
            - name: 'Installing SFDX scanner'
              run: sfdx plugins:install @salesforce/sfdx-scanner

            # https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm
            # This URL can then be used with the sfdx auth:sfdxurl:store to
            # authenticate the sfdx project in the repositry, against the UAT Org.

            # The UAT Org auth URL is stored in the Github Secret named SFDX_STAGING_URL
            # We will store the URL into a text file
            - name: 'Populate auth file with SFDX_URL secret of UAT org'
              shell: bash
              run: |
                  echo ${{ secrets.SFDX_STAGING_URL}} > ./SFDX_STAGING_URL.txt
                  secretFileSize=$(wc -c "./SFDX_STAGING_URL.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing SFDX_STAGING_URL secret. Is this workflow running on a fork?";
                      exit 1;
                  fi

            # Authenticate to org using the URL stored in the text file
            - name: 'Authenticate to UAT Org (Staging)'
              run: sfdx auth:sfdxurl:store -f ./SFDX_STAGING_URL.txt -s -a ${{ env.STG_ORG_ALIAS }}

            # We use SFDX Git Delta to create a directory with only the metadata that has changed.
            # this allows us to deploy only those changes, as opposed to deploying the entire branch.
            # This helps reducing deployment times.
            - name: 'Create delta packages for new, modified or deleted metadata'
              run: |
                  mkdir changed-sources
                  sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ --ignore .sgdignore
                  cat ./changed-sources/**/package.xml
                  cat ./changed-sources/**/destructiveChanges.xml

            # Now we can use the sfdx scanner to scan the code in the delta directory
            # The output of the scan is stored in a file called apexScanResults.csv

            # The .xml file can later be uploaded to github, so that we can see the
            # results of the scan directly from the PR.
            - name: 'Scan code'
              id: scan-results
              run: |
                  cd changed-sources
                  sfdx scanner:run --format csv --target './**/*.cls' --severity-threshold 3 --outfile 'apexScanResults.csv'  
                  cd ..

            # Read PMD csv file results
            - name: 'Read Results CSV'
              if: failure() && steps.scan-results.outcome == 'failure'
              id: csv
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./changed-sources/apexScanResults.csv

            ## Create table markdown from csv results
            - name: 'Create Markdown table'
              if: failure() && steps.csv.outcome == 'success' && steps.scan-results.outcome == 'failure'
              uses: petems/csv-to-md-table-action@master
              id: csv-table-output
              with:
                  csvinput: ${{ steps.csv.outputs.content }}

            # Upload the .csv file as a table to PR comments
            - name: 'Upload PMD Results on PR'
              if: failure() && steps.csv-table-output.outcome == 'success' && steps.scan-results.outcome == 'failure'
              uses: mshick/add-pr-comment@v1
              with:
                  message: |
                      ${{steps.csv-table-output.outputs.markdown-table}}
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  allow-repeats: true

            # Check-only deployment and run all tests
            - name: 'Check-Only deploy delta changes - run all tests'
              run: |
                  sfdx force:source:deploy --manifest "changed-sources/package/package.xml" --postdestructivechanges "changed-sources/destructiveChanges/destructiveChanges.xml" --checkonly --testlevel RunLocalTests  --json --ignorewarnings

```
