### ISSUE TITLE
CI/CD Pipeline Broken Due to --target Parameter Enforcement in Version 4.3.2

### ISSUE THREAD

**Issue by adityasfdev** [forcedotcom/sfdx-scanner#1536]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

- We are experiencing issues with the Salesforce Scanner plugin (version 4.3.2) in our CI/CD pipeline. The pipeline, which previously worked fine with version 4.3.0, is now failing due to the enforced requirement of the --target parameter to contain at least one file. - Our pipeline runs three separate commands to validate Apex classes, Aura components, and LWC components. This is necessary because we cannot predict which files a developer might commit. The enforced --target parameter now requires each command to include at least one file, causing the pipeline to break when there are no files in one or more of these components.

**Pipeline Commands:** 

1. sfdx scanner:run --target "**classes**" --format json 
2. sfdx scanner:run --target "**aura**" --format json 
3. sfdx scanner:run --target "**lwc**" --format json 

-  Error (1): No files were found in the target. --target must contain at least one file.

### Steps To Reproduce

1. Set up a CI/CD pipeline with the Salesforce Scanner plugin version 4.3.2.
2. Run the commands for each component (Apex classes, Aura components, LWC components) in the pipeline.
3. Ensure one or more of these components have no files.
4. Observe the error due to the --target parameter enforcement.

### Expected Behavior

The commands should run successfully even if one or more components have no files, as it worked in version 4.3.0.

### Operating System

ubuntu-latest in Azure pipeline 

### Salesforce CLI Version

@salesforce/cli/2.47.6 linux-x64 node-v18.20.3

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

v4.3.2

### Workaround

As a temporary fix, we have downgraded the Salesforce Scanner plugin to version 4.3.0. This allows our pipeline to run successfully without requiring the --target parameter to contain at least one file.

### Urgency

High

**Comment by stephen-carter-at-sf** [comment]
Thanks for letting us know. For now instead of moving to 4.3.0 - you can use the latest but specify your project directory with your call. If it is just the present working directory, then use `--projectdir .`

**Comment by stephen-carter-at-sf** [comment]
Since this only impacts users targetting empty files without supplying a --projectdir, we will not rush out a patch release for this fix. Instead, this fix will go out with out 4.4.0 release at the end of this month.

**Comment by rosangelys-pfm** [comment]
@adityasfdev 
Hi, I faced the same problem, and as it is a high priority on my side because I am using the sfdx scanner in my CI/CD github pipeline for specific files I found this workaround:

Use the following extension to check the existence of the files in your workflow:
https://github.com/marketplace/actions/file-existence

This is how I use it:

1. Check in my changed-sources library if there are any .cls files changed (changed files provided by git-delta)
2. If I have .cls files changed, I will run the scanner other wise skip that step.

```
 # Check if cls files are present in the changed sources directory.
            - name: 'Check CLS file existence'
              id: check_files
              uses: andstor/file-existence-action@v3
              with:
                  files: 'changed-sources/**/*.cls'

            # The .xml file can later be uploaded to github, so that we can see the
            # results of the scan directly from the PR.
            - name: 'Scan code'
              id: scan-results
              if: steps.check_files.outputs.files_exists == 'true'
              run: |
                  cd changed-sources
                  sfdx scanner:run --format csv --target './**/*.cls' --severity-threshold 3 --outfile 'apexScanResults.csv'  
                  cd ..
```
