### ISSUE TITLE
[BUG] Cannot execute PMD scan with custom XML rules

### ISSUE THREAD

**Issue by db-lyon** [forcedotcom/sfdx-scanner#1700]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

1. PMD is running
2. My rules have been registered successfully
3. My rules are evaluating my files successfully
4. My rules are failing silently
5. I need help

### Output / Logs

[This gist has it all!](https://gist.github.com/db-lyon/39794e7f3fb9c7da68b4e3cae6a13290)

### Setup
1. Define the following ruleset: `./category/xml/metadata.xml` [ [relevant gist](https://gist.github.com/db-lyon/39794e7f3fb9c7da68b4e3cae6a13290#file-metadata-xml) ]
2. Run `sf scanner rule add -l xml -p category/xml/metadata.xml`
3. Run `sf scanner rule list --category metadata`
4. Confirm `~.sfdx-scanner/Config.json` isn't exclusing `*-meta.xml` [ [relevant gist](https://gist.github.com/db-lyon/39794e7f3fb9c7da68b4e3cae6a13290#file-config-json) ]
5. Verify the rules have been registered:
```
 name                         languages categories rulesets [dep] engine is dfa is pilot 
 ──────────────────────────── ───────── ────────── ────────────── ────── ────── ──────── 
 NoUnderscoresInFieldNames    xml       metadata                  pmd    N      N
 NoFieldPermissionsInProfile  xml       metadata                  pmd    N      N
 NoObjectPermissionsInProfile xml       metadata                  pmd    N      N
 CustomFieldNamingConvention  xml       metadata                  pmd    N      N
 ```
### Test
1. Open my sf project
2. Run `sf scanner run --target "force-app/main/default/objects" --engine pmd --json --verbose`
3. Note the following output:
```json
{
  "status": 0,
  "result": "Executed engines: pmd. No rule violations found.",
  "warnings": [
    "We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at http://sfdc.co/CodeAnalyzerFeedback",
    "Cataloger: Dropping XML file [META-INF/maven/net.sourceforge.pmd/pmd-xml/pom.xml] since its path does not conform to Rulesets or Category.",
    "Cataloger: Dropping XML file [META-INF/maven/net.sourceforge.pmd/pmd-apex/pom.xml] since its path does not conform to Rulesets or Category."
  ]
}
```

### Sanity Check
1. Open `./category/xml/metadata.xml`
2. Uncomment the ["HelloWorld"](https://gist.github.com/db-lyon/39794e7f3fb9c7da68b4e3cae6a13290#file-metadata-xml-L10-L22) rule
3. Run `sf scanner run --target "force-app/main/default/objects" --category metadata --engine pmd --json --verbose --outfile hello-world-results.json`
4. Note the following output [ [relevant gist](https://gist.github.com/db-lyon/39794e7f3fb9c7da68b4e3cae6a13290#file-hello-world-results-json) ]

### Expected Behavior

I expect some violations. 
I don't want to upload any actual `-meta.xml` files but suffice it to say I expect to see MANY violations.

edit: I created the following test field: `./force-app/main/default/objects/Account/fields/This_Should_Trigger_A_Violation__c.field-meta.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>This_Should_Trigger_A_Violation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>This Should Trigger a Violation </label>
    <trackFeedHistory>true</trackFeedHistory>
    <type>Checkbox</type>
</CustomField>
```

### Operating System

Windows 11 (64)

### Salesforce CLI Version

@salesforce/cli/2.68.6 win32-x64 node-v18.18.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.7.0

### Workaround

N/A

### Urgency

Critical

**Comment by stephen-carter-at-sf** [comment]
Hello. Did you try running these rules with PMD first (without code analyzer in the mix)?

Also, soon we will be moving all of our support to Code Analyzer 5 where we have much better custom PMD rule support. So can you also try installing the `code-analyzer` plugin (see https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/version-5-setup.html) and then creating a code-analyzer.yml file that contains:
```
engines:
  pmd:
    # List of jar files and/or folders to add the Java classpath when running PMD.
    # Each entry may be given as an absolute path or a relative path to 'config_root'.
    # This field is primarily used to supply custom Java based rule definitions to PMD.
    # See https://pmd.github.io/pmd/pmd_userdocs_extending_writing_java_rules.html
    java_classpath_entries: []

    # List of xml ruleset files containing custom PMD rules to be made available for rule selection.
    # Each ruleset must be an xml file that is either:
    #   - on disk (provided as an absolute path or a relative path to 'config_root')
    #   - or a relative resource found on the Java classpath.
    # Not all custom rules can be fully defined within an xml ruleset file. For example, Java based rules may be defined in jar files.
    # In these cases, you will need to also add your additional files to the Java classpath using the 'java_classpath_entries' field.
    # See https://pmd.github.io/pmd/pmd_userdocs_making_rulesets.html to learn more about PMD rulesets.
    custom_rulesets: []
```
where you add in your custom_rulesets there. Then try out the `sf code-analyzer rules -r pmd:Recommended` command to see if it detects your rules. Then try running them with `sf code-analyzer rules -r pmd:Recommended -w <your_workspace>`, etc.
