### ISSUE TITLE
[BUG][scanner run] `sf code-analyzer run ...` causes Windows Defender to spike the CPU

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/sfdx-scanner#1796]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Anytime that I run `sf code-analyzer run ...`, I almost immediately see a CPU spike, and `MsMpEng` is right alongside the host `node` process in CPU consumption:

![Image](https://github.com/user-attachments/assets/ee30d7b6-7d7f-4ca9-93d7-5f08baa7ea53)

The directory containing Salesforce projects is already in the exclusion list, and I don't see any issues running other `sf` commands from these projects. I'm guessing that something else being executed by Code Analyzer needs to be excluded, no? Any idea what that would be? I'm not comfortable excluding `node` altogether for what I hope are obvious reasons.

### Output / Logs

I also timed command execution with and without Defender active, and the impact is pretty significant:

**Defender enabled:** 2m6.395s
**Defender disabled:** 0m49.501s

### Steps To Reproduce

Run Code Analyzer on Windows with Defender enabled.

### Expected Behavior

There's some safe way to configure Windows Defender exclusions so that Code Analyzer can run without spiking the CPU.

### Operating System

Windows 11 

### Salesforce CLI Version

@salesforce/cli/2.87.7 win32-arm64 node-v22.13.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

code-analyzer 5.0.0 (5.0.0)

### Urgency

Low

**Comment by stephen-carter-at-sf** [comment]
@SCWells72 did you experience the same issue with the (v4) `sf scanner` commands as well?

If you do not want to exclude the node_modules/@salesforce folder from windows defender, then maybe you can help narrow down the problem a bit.

First start with a [code-analyzer.yml ](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/config-custom.html) file that disabled all the engines. Then one at a time enable just the one engine. Each time just run with just that one engine enabled only. See if there is a specific engine that is causing the Windows Defender spike.

For example start with:
```
engines:
  cpd:
    disable_engine: false
  pmd:
    disable_engine: true
  eslint:
    disable_engine: true
  regex:
    disable_engine: true
  retire-js:
    disable_engine: true
  flow:
    disable_engine: true
  sfge:
    disable_engine: true
```
to just run the cpd engine and see if that spikes Windows Defender.

Then run with
```
engines:
  cpd:
    disable_engine: true
  pmd:
    disable_engine: false
  eslint:
    disable_engine: true
  regex:
    disable_engine: true
  retire-js:
    disable_engine: true
  flow:
    disable_engine: true
  sfge:
    disable_engine: true
```
to just run the pmd engine and see if that spikes Windows Defender.

and do that for all the engines.

Most of us here at Salesforce do not have Windows machines with Windows Defender - so we appreciate the help in seeing what is possible causing the spike.

I have some hunches (that is just the engines doing their jobs) but I'm curious to see what you find first before I give my hunches.
